### DISCUSSION TITLE
模型运行的 CUDA error: device-side assert相关问题

### DISCUSSION THREAD

**Discussion by flowbywind** [zai-org/ChatGLM3#393] [Bad Case]
模型部署后调用了几百次没问题 但再调用就报了这个错误 
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "get_api_cuda1.py", line 66, in create_item
    response, history = model.chat(tokenizer,
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1032, in chat
    inputs = inputs.to(self.device)
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 758, in to
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
  File "/usr/local/anaconda3/envs/chatglm/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 758, in <dictcomp>
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by hxujal** [comment]
我也出现了同样的问题

**Comment by jeinlee1991** [comment]
```
File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1038, in chat
    outputs = self.generate(**inputs, **gen_kwargs, eos_token_id=eos_token_id)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 1522, in generate
    return self.greedy_search(
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 2339, in greedy_search
    outputs = self(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 937, in forward
    transformer_outputs = self.transformer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 830, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 640, in forward
    layer_ret = layer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 542, in forward
    layernorm_output = self.input_layernorm(hidden_states)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 190, in forward
    hidden_states = hidden_states * torch.rsqrt(variance + self.eps)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

我也出现了同样的问题

**Comment by Hcnaeg** [comment]
同样问题

**Comment by hubo0417** [comment]
怎么解决呢？

**Comment by BeiJingChengXiTech** [comment]
glm官方，能快速解决这个问题不？？？

**Comment by YiFraternity** [comment]
是这样的，也是遇到这个问题

**Comment by lanxinlo** [comment]
我也遇到这个问题 怎么解决哇

**Comment by qzl164** [comment]
同样遇到了，求解

**Comment by zRzRzRzRzRzRzR** [comment]
mark，我们抓紧解决这个问题

**Reply by htlyaaaa** [reply]
gkd

**Comment by Btlmd** [comment]
目前我暂时没能复现这个问题。这里 CUDA 的报错是异步的，是否有人可以在设置了 `CUDA_LAUNCH_BLOCKING=1` 环境变量的情况下，定位一下问题的产生位置？

**Comment by Btlmd** [comment]
我在一种情况下复现了这种问题。一种可能的原因是输入序列的长度超过了模型的 position embedding 的最大长度，造成索引时超范围了。

在 `composite_demo` 中引入了更加友善的错误提示。

**Reply by BLANKBLK** [reply]
怎么解决输入序列长度超过模型positon embedding的问题呢？

**Comment by tjgaozw** [comment]
我也出现了这个问题，出现了很多次，多轮对话后出现，显存也没有爆

**Comment by worm128** [comment]
一样的问题，用model.stream_chat流输出字符串没问题，用model.chat整段字符串输出就报错，断点到源码看，看起来像是数组越界
调试代码得知：
错误文件：.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py
代码错误行：723行代码报错 words_embeddings = self.word_embeddings(input_ids)
错误信息：pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\Indexing.cu:1239: block: [28,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

![微信图片_20231110082442](https://github.com/THUDM/ChatGLM3/assets/29749635/37690ca1-5602-4b4e-a68c-f80578576bcc)
![QQ图片20231110081506](https://github.com/THUDM/ChatGLM3/assets/29749635/6d69969a-ca20-4b54-b203-be2bb7d16679)

**Comment by worm128** [comment]
> `TORCH_USE_CUDA_DSA`

看我错误报告 #243

**Comment by worm128** [comment]
> mark，我们抓紧解决这个问题

看我错误报告 #243

**Comment by qzl164** [comment]
> 同样遇到了，求解

设置了 TORCH_USE_CUDA_DSA=1 环境变量后的报错如下：
[2023-11-10 14:15:27,541] ERROR in app: Exception on /chat [POST]
Traceback (most recent call last):
  File "/data/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/data/project/chatglm3-code/flask_stream_glm3_main-code2.py", line 149, in chatGLM
    response, history = model.chat(tokenizer, query, history=history, max_length=max_len, temperature=temperature)
  File "/data/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/useradmin/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1104, in chat
    outputs = self.generate(**inputs, **gen_kwargs, eos_token_id=eos_token_id)
  File "/data/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/miniconda3/lib/python3.8/site-packages/transformers/generation/utils.py", line 1648, in generate
    return self.sample(
  File "/data/miniconda3/lib/python3.8/site-packages/transformers/generation/utils.py", line 2730, in sample
    outputs = self(
  File "/data/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/useradmin/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 938, in forward
    transformer_outputs = self.transformer(
  File "/data/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/useradmin/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 824, in forward
    rotary_pos_emb = rotary_pos_emb[position_ids]
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by tjgaozw** [comment]
还没解决啊？

**Comment by xx1906** [comment]
```
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [0,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [1,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [2,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [3,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [4,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [5,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [6,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [7,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [8,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [9,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [10,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [11,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [12,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [13,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [14,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [15,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [16,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [17,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [18,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [19,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [20,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [21,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [22,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [23,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [24,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [25,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [26,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [27,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [28,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [29,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [30,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [1162,0,0], thread: [31,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

``` 
类似的问题

**Reply by Crily11** [reply]
我也是这个问题 请问你解决了吗

**Comment by xx1906** [comment]
The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/xx/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 178, in apply_rotary_pos_emb
    )
    x_out2 = x_out2.flatten(3)
    return torch.cat((x_out2, x_pass), dim=-1)
           ~~~~~~~~~ <--- HERE
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


done....
The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/xx/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 178, in apply_rotary_pos_emb
    )
    x_out2 = x_out2.flatten(3)
    return torch.cat((x_out2, x_pass), dim=-1)
           ~~~~~~~~~ <--- HERE
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Btlmd** [comment]
是否可以提供报错的那一次 `forward` 给模型传入的 `input_ids` 的 shape 和 `input_ids.tolist()` 的结果？如果长度超过 positional embedding 的最大长度那就是输入长度的问题。如果不是，我可以使用相同的 `input_ids` 试一试

**Comment by ycjcl868** [comment]
同样问题

Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

**Comment by zRzRzRzRzRzRzR** [comment]
该问题为bad case，目前版本难以解决，已经移动到Discussion并记录为之后模型升级的方向

**Reply by tjgaozw** [reply]
那这个ChatGLM3不能用了？

**Reply by zRzRzRzRzRzRzR** [reply]
我们甚至不知道在什么情况下能稳定复现这个问题，我们服务器为Ubuntu22.04 cuda 12.3 torch2.1 
@Btlmd 曾经在一种情况能复现，但是是输入序列的长度超过了模型的 position embedding 的最大长度。并不是启动就死了

**Reply by doubleTaoTao** [reply]
官方请问这个问题解决了吗?

**Comment by wuyiclover** [comment]
<img width="799" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/37546904/9001efb6-e214-4e17-9c24-f3991ccd185d">

822行  seq_length为config中默认的8192
如果输入长度超过8192，会引发824行的索引错误

![image](https://github.com/THUDM/ChatGLM3/assets/37546904/ac90fd18-5baf-4303-bf59-c8fbea99d373)

**Comment by zRzRzRzRzRzRzR** [comment]
今天更新了一下模型配置文件，查看一下问题是否还在

**Reply by YLiberals** [reply]
仍然存在

**Reply by zRzRzRzRzRzRzR** [reply]
emm，怎么复现，我们在linux 和mac都试过，没有问题

**Reply by YLiberals** [reply]
是这样的，我的环境是在ubuntu的docker中，具体是：1、使用了LLaMA-Factory项目进行了LoRA微调；2、使用LLaMA-Factory中提供的api服务进行访问微调的glm3-6b。在序列长度较长的情况下就会出现这个问题。之前已经在LLaMA-Factory项目的Issue中进行了查询，说是glm3的问题，可以使用LLaMA-Factory的api试试能不能够复现这个问题

**Comment by bearbee123** [comment]
我也会出现这样的情况，特别是在每一次进行对话显存的占用都会上升，但结束这轮对话后，显存会降到原来刚加载模型时侯的显存占用，如果再进行对话则显存会比上一次对话时候的显存占用还要大
![29c38a52-3314-428e-8a22-6e23ed595512](https://github.com/THUDM/ChatGLM3/assets/79078255/c3e4b90e-28db-45e4-a316-f99bd8b16360)
![339c9de7-3000-4e8a-a1cc-780157ccada7](https://github.com/THUDM/ChatGLM3/assets/79078255/c1985831-14f1-4480-9170-85d67a17dcbe)
是我的代码逻辑有问题么，后面尝试加入如下图的索引要求后会有所改善[]
![929cf330-66be-4999-83f4-8ea070dfec9d](https://github.com/THUDM/ChatGLM3/assets/79078255/75ad91a5-c866-451c-b2d0-4d408208b7b7)
求助！

**Comment by worm128** [comment]
> 今天更新了一下模型配置文件，查看一下问题是否还在
你们用window11测试一下，应该就能复现这个问题

**Reply by zRzRzRzRzRzRzR** [reply]
emm，我没有windows电脑，在mac 和Linux没有出现

**Reply by tinkball** [reply]
它在问答次数少的情况下是不会出现的，需要进行至少200次的问答，才会出现

**Reply by treya-lin** [reply]
> 它在问答次数少的情况下是不会出现的，需要进行至少200次的问答，才会出现

不，我遇到的几次都是极少轮就会出现。

**Comment by zhang-xh95** [comment]
有没有chatGLM2-6B也遇到同样问题的

**Reply by lrh000** [reply]
一样的

**Comment by 10cent01** [comment]
你好，我在循环调用stream_chat时 也出现了同样的问题。在到了大约114条输入时，报出提示：``Input length of input_ids is 32802, but `max_length` is set to 32768. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.`` ，随后报出跟上面类似的cuda越界错误。

我尝试按照给的提示修改`max_length `和 `max_new_tokens`，问题依然存在。然后我在modelling_chatglm.py的stream_generate()函数中打印： `batch_size, input_ids_seq_length = input_ids.shape[0], input_ids.shape[-1]`， 结果大致为：

![image](https://github.com/THUDM/ChatGLM3/assets/40633951/518cbae7-ada2-49c4-84a7-48f3801e06ee)

`input_ids_seq_length `，即`input_ids.shape[-1]` 的值从360增长到3万多。而我记起之前使用GLM2的时候没有遇到过这种问题，我也顺便添加了一下打印，发现这个值一直在400-600之间上下徘徊，而不像GLM3这里稳定增长。

**Reply by 10cent01** [reply]
input_ids_seq_length 的问题，是 stream_chat 里 past_key_values 参数导致的，似乎跟CUDA报错没有联系。

**Comment by treya-lin** [comment]
same error. :( 刚开始尝试使用就遇到了。

环境：我在ubuntu 22.04 的 docker 内 （cuda118， torch210），显卡4090*1 ，没有修改过模型。

另外并不是超多轮问答才会出现，我三四轮就会遇到。贴一个聊天记录吧，就：(我之前还遇到过更短的对话，从第三轮就开始出现问题的，没记下来。）

```
== Input ==
 你好

==History==
 [{'role': 'system', 'content': "You are ChatGLM3, a large language model trained by Zhipu.AI. Follow the user's instructions carefully. Respond using markdown."}]

== Input ==
 你知道什么是语音转换吗？

==History==
 [{'role': 'system', 'content': "You are ChatGLM3, a large language model trained by Zhipu.AI. Follow the user's instructions carefully. Respond using markdown."}, {'role': 'user', 'content': '你好'}, {'role': 'assistant', 'content': '你好！有什么可以帮助您的吗？'}]

== Input ==
 你对现在比较流行的RAG技术有什么看法？你认为什么时候适合RAG,什么适合finetuning？

==History==
 [{'role': 'system', 'content': "You are ChatGLM3, a large language model trained by Zhipu.AI. Follow the user's instructions carefully. Respond using markdown."}, {'role': 'user', 'content': '你好'}, {'role': 'assistant', 'content': '你好！有什么可以帮助您的吗？'}, {'role': 'user', 'content': '你知道什么是语音转换吗？'}, {'role': 'assistant', 'content': '语音转换是一种将语音信号转换为其他格式的技术，常见的有文本、文字或指令等。它可以通过算法实现，也可以通过人机
  互完成。例如，一些智能助手可以识别用户的声音并回答问题。'}]

== Input ==
 如果有一个需求，要做一个可以离线部署的AI的对话机器人，需要能够根据公司内部的文档，进行知识问答，你认为应该需要准备什么数据，然后用什么技术来实现呢？

==History==
 [{'role': 'system', 'content': "You are ChatGLM3, a large language model trained by Zhipu.AI. Follow the user's instructions carefully. Respond using markdown."}, {'role': 'user', 'content': '你好'}, {'role': 'assistant', 'content': '你好！有什么可以帮助您的吗？'}, {'role': 'user', 'content': '你知道什么是语音转换吗？'}, {'role': 'assistant', 'content': '语音转换是一种将语音信号转换为其他格式的技术，常见的有文本、文字或指令等。它可以通过算法实现，也可以通过人机
  互完成。例如，一些智能助手可以识别用户的声音并回答问题。'}, {'role': 'user', 'content': '你对现在比较流行的RAG技术有什么看法？你认为什么时候适合RAG,什么适合finetuning？'}, {'role': 'assistant', 'content': 'RAG（Reinforcement Learning based Approach for Generative Modeling）是一种基于强化学习的生成模型方法，它在近年来受到了越来越多的关注。它的核心思想是通过训练一个强化学习模型来引导生成模型产生高质量的样本。相比之下，Fine-tuning是一种使用预训练模型来微调以特定
  务进行更好的方法。\n\n对于何时适合RAG和何时适合Fine-tuning，这取决于具体情况和需求。总的来说，如果需要快速获得一个能够产生良好结果的模型，并且数据量有限，那么Fine-tuning可能是一个更好的选择。这是因为Fine-tuning利用了预训练模型的知
  ，可以在较短的时间内获得较好的性能。\n\n相反，如果需要处理大量数据或者希望模型具有更高的泛化能力，那么RAG可能会更适用。RAG可以通过强化学习模型来更好地引导生成模型，从而在长期内获得更好的性能。\n\n当然，在实际应用中，最好的方法是尝
  多种方法并比较它们的性能，然后根据结果选择最适合的方法。'}]
2024-02-05 07:25:42.879 Uncaught app exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/main.py", line 72, in <module>
    demo_chat.main(
  File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/demo_chat.py", line 62, in main
    for response in client.generate_stream(
  File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/client.py", line 183, in generate_stream
    for new_text, _ in stream_chat(
  File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/client.py", line 110, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 1169, in stream_generate
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 97, in __call__
    scores = processor(input_ids, scores)
  File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/client.py", line 56, in __call__
    if torch.isnan(scores).any() or torch.isinf(scores).any():
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


```
而且最后一轮不是直接报错，是生成了一阵子才报错。
![image](https://github.com/THUDM/ChatGLM3/assets/86940562/0393e3eb-78be-4e49-a7cf-ad2d38a3ec8b)

**Reply by treya-lin** [reply]
另一个badcase。
另外，虽然最后都是报的an illegal memory access was encountered，但是traceback每次也不一样的？我就是用单纯的chat功能而已呢。

```
==History==
 [{'role': 'system', 'content': "You are ChatGLM3, a large language model trained by Zhipu.AI. Follow the user's instructions carefully. Respond using markdown."}, {'role': 'user', 'content': '你的知识最新更新到什么时候？'}, {'role': 'assistant', 'content': '我的知识库最
近一次的更新时间是2022年1月。虽然不能保证每个问题的答案都最准确，但我已经具备了相当程度的知识来回答各种问题。如果您有疑问，欢迎随时向我提问！'}, {'role': 'user', 'content': '你知道openai吗'}, {'role': 'assistant', 'content': 'OpenAI是一个总部位于美国的人工智能研究公司，成立于2015年。OpenAI的目标是实现安全的通用人工智能（AGI）并让其有益于人类。OpenAI的研究范围包括人工智能的各个方面，例如机器学习、自然语言处理、计算机视觉等。OpenAI的研究成果和论文经常被业界和学术界引用，并且该公司的技术也受到了广泛的关注和使用。'}, {'role': 'user', 'content': '你知道openai最新的产品是什么吗？'}, {'role': 'assistant', 'content': '是的，OpenAI 经常发布新的产品和功能。截至我知識截止日期2022年1月，OpenAI 的最新产品包括：\n\n* GPT-3：一个基于深度学习的自然语言处理模型，可以生成高质量的自然语言文本。GPT-3是OpenAI 公司的一款重要产品，也是世界上最大的公开可用的自然语言处理模型之一。\n* GPT-2：一个基于深度学习的自然语言处理模型，比GPT-3小一些，但仍然具有非常强大的语言生成能力。GPT-2可以用于许多不同的应用程序，包括自然语言生成、对话系统、文本摘要等。\n* Transformer：一种基于自注意力机制的神经网络结构，广泛应用于自然语言处理领域。Transformer 模型的出现极大地提高了深度学习在自然语言处理方面的表现。\n*自动机器学习（AutoML）：OpenAI 的自动机器学习平台，使研究人员和开发人员能够快速轻松地构建和训练机器学习模型。AutoML 可以用于许多不同的应用程序，包括图像识别、自然语言处理
、推荐系统等。\n\n这只是OpenAI 的部分产品和服务，OpenAI 还有许多其他的产品和服务正在开发中。'}, {'role': 'user', 'content': '你知道openai有什么语音方面的产品或服务吗'}, {'role': 'assistant', 'content': '是的，OpenAI 提供了一些与语音相关的产品和服务。其中最著名的是其语音合成技术，可以使用 deep text-to-speech （TTS）模型将文本转换为自然语音。这种技术可以应用于许多不同的应用程序，包括虚拟助手、语音翻译、朗读、导航等。\n\n此外，OpenAI 还提供了一个叫做“声音”的 API，可以用于在应用程序中添加背景音乐和其他音频效果。这个 API 可以与 TTS 技术一起使
用，创建更加真实和自然的语音交互体验。\n\n除此之外，OpenAI 还在研究和开发其他与语音相关的技术和产品，例如语音识别和语音情感分析等。'}]
2024-02-05 07:50:08.688 Uncaught app exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/main.py", line 72, in <module>
    demo_chat.main(
  File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/demo_chat.py", line 62, in main
    for response in client.generate_stream(
  File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/client.py", line 183, in generate_stream
    for new_text, _ in stream_chat(
  File "/home/dev/workspace/llm_space/ChatGLM3/composite_demo/client.py", line 110, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 1159, in stream_generate
    outputs = self(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 937, in forward
    transformer_outputs = self.transformer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 830, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 640, in forward
    layer_ret = layer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 544, in forward
    attention_output, kv_cache = self.self_attention(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 415, in forward
    value_layer = torch.cat((cache_v, value_layer), dim=0)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

**Comment by Longleaves** [comment]
用微调模型批量推理同样报错，怎么解决呀，感谢各位大佬！
应该不是输入长度问题，我的提问很短的，但是涉及隐私信息不方便发出来。

报错信息：
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [0,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [1,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [2,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
……
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/a3fba14a-5008-4c97-a29d-201ab03dc29c)

**Reply by xingyunjohn1** [reply]
I had the same problem.

**Reply by wududu123** [reply]
I had the same problem. if running on cpu:

 7 in embedding                                                                                   │
│                                                                                                  │
│   2234 │   │   #   torch.embedding_renorm_                                                       │
│   2235 │   │   # remove once script supports set_grad_enabled                                    │
│   2236 │   │   _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)                    │
│ ❱ 2237 │   return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)        │
│   2238                                                                                           │
│   2239                                                                                           │
│   2240 def embedding_bag(                                                                        │

IndexError: index out of range in self

**Reply by lrh000** [reply]
+1

**Reply by ljc010717** [reply]
+1

**Comment by liujingmao** [comment]
我也遇到了这个问题,希望官方能够快点解决这个问题

**Comment by AI-student2024** [comment]
我直接在开源项目中执行这个文件：https://github.com/THUDM/ChatGLM3/blob/main/finetune_demo/lora_finetune.ipynb，也遇到了同样的报错。部分信息如下：/root/miniconda3/envs/chatglm/lib/python3.11/site-packages/torch/nn/modules/module.py:1511 in    │
│ _wrapped_call_impl                                                                               │
│                                                                                                  │
│   1508 │   │   if self._compiled_call_impl is not None:                                          │
│   1509 │   │   │   return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]        │
│   1510 │   │   else:                                                                             │
│ ❱ 1511 │   │   │   return self._call_impl(*args, **kwargs)                                       │
│   1512 │                                                                                         │
│   1513 │   def _call_impl(self, *args, **kwargs):                                                │
│   1514 │   │   forward_call = (self._slow_forward if torch._C._get_tracing_state() else self.fo  │
│                                                                                                  │
│ /root/miniconda3/envs/chatglm/lib/python3.11/site-packages/torch/nn/modules/module.py:1520 in    │
│ _call_impl                                                                                       │
│                                                                                                  │
│   1517 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1518 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1519 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1520 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1521 │   │                                                                                     │
│   1522 │   │   try:                                                                              │
│   1523 │   │   │   result = None                                                                 │
│                                                                                                  │
│ /root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py:822 in     │
│ forward                                                                                          │
│                                                                                                  │
│    819 │   │   │   │   │   │   │   │   │   │   │   attention_mask], dim=-1)                      │
│    820 │   │                                                                                     │
│    821 │   │   if full_attention_mask is None:                                                   │
│ ❱  822 │   │   │   if (attention_mask is not None and not attention_mask.all()) or (past_key_va  │
│    823 │   │   │   │   full_attention_mask = self.get_masks(input_ids, past_key_values, padding  │
│    824 │   │                                                                                     │
│    825 │   │   # Rotary positional embeddings                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Reply by hanke3** [reply]
相同的错误

**Reply by Win7win** [reply]
同样遇到这个问题

**Comment by liujingmao** [comment]
python inference_hf.py your_finetune_path --prompt your prompt 执行这个命令的时候,也会报这个

**Reply by hanke3** [reply]
相同的错误

**Comment by hanke3** [comment]
用chatglm3官方代码进行lora微调，微调能成功，但是用官方的lora_finetune.ipynb 中的方式： “python3 inference_hf.py 微调后的模型输出目录   --prompt 输入prompt”  进行推理，就报上述错误了。

**Reply by hanke3** [reply]
解决了，需要
transformer==4.38.1
peft==0.7.1
accelerate==0.27.2
然后重新微调模型，就可以正常加载模型进行推理了。

**Reply by xmy89929** [reply]
解决了！感谢

**Reply by Win7win** [reply]
确实是环境的问题，感谢！

**Comment by liujingmao** [comment]
听有的同学说修改peft版本为0.9这个版本没有这个问题,但是要重新微调!

**Reply by MCJiu** [reply]
试了一下，还是同样的错误

**Reply by liujingmao** [reply]
我昨天重新微调了,微调都报错了!

**Reply by Wenting1227** [reply]
您好，想问一下您最后是怎么解决的呢？

**Comment by jeinlee1991** [comment]
是参数history的问题，history初始值可以设为None，但千万别设为[]

**Reply by hanke3** [reply]
你的问题解决了？看代码None会被赋值成[]
![image](https://github.com/THUDM/ChatGLM3/assets/34292769/60cfe939-5b35-4c51-9f0f-af820bc38a71)

**Reply by worm128** [reply]
我已经放弃glm3了

**Reply by Win7win** [reply]
尝试修改history=[]为None，会提示不能append，改成[{"role": "user", "content": "你好"}]还是会报错，求解orz

**Reply by worm128** [reply]
用流式输出的方法就不会错了，还不如用千问1.5，放弃了，太多bug

**Reply by hanke3** [reply]
试试这个环境，我可以正常推理了。
transformer==4.38.1
peft==0.7.1
accelerate==0.27.2

**Reply by liujingmao** [reply]
我昨天按照官网githup上的方法，也是微调和推理成功了

**Reply by NLP-1217** [reply]
用的什么依赖？

**Comment by zzk2021** [comment]
GLM4也是一样的，我用llama factory微调，但是llama factory只能peft>0.11

**Comment by yhyayi** [comment]
使用 glm-4v-9b 微调的 cogagent 也同样有这个问题，请问现在有什么解决方案吗

**Reply by zzk2021** [reply]
> 使用 glm-4v-9b 微调的 cogagent 也同样有这个问题，请问现在有什么解决方案吗

我找到原因是合并lora权重造成的，如果不合并就不会报错
